imu:
  package: 'rpm_sensors'
  driver_package: 'bluespace_ai_xsens_mti_driver'
  executable: 'xsens_mti_node'
  launch_file: 'imu_launch.py'
  name: 'xsens_mti_node'
  namespace: 'rpm/sensors/front/imu'
  parameters: 'xsens_mti_node.yaml'
lidar_front:
  package: 'rpm_sensors'
  driver_package: 'ros2_ouster'
  executable: 'ouster_driver'
  launch_file: 'lidar_launch.py'
  name: 'ouster_driver'
  namespace: 'rpm/sensors/front/lidar3d'
  parameters: 'bautiro_ouster_os0-64.yaml'
lidar_rear:
  package: 'rpm_sensors'
  driver_package: 'ros2_ouster'
  executable: 'ouster_driver'
  launch_file: 'lidar_launch.py'
  name: 'ouster_driver'
  namespace: 'rpm/sensors/rear/lidar3d'
  parameters: 'bautiro_ouster_os0-64.yaml'