/rpm_velocity_controller:
  ros__parameters:
    use_sim_time: false
    update_rate: 1     # For some reason, lower the update rate, higher the frequency of odom message received

    type: diff_drive_controller/DiffDriveController

    left_wheel_names: [ "left_wheel_joint"]
    right_wheel_names: [ "right_wheel_joint" ]

    wheel_separation: 0.6  #0.1  # 0.256  # 0.512
    wheel_per_side: 1
    wheel_radius: 0.125 # 50% of wheelDiameter in rpm_description/urdf/rpm_macro.urdf.xacro

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: True
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Preserve turning radius when limiting speed/acceleration/jerk
    preserve_turning_radius: true

    # Publish limited velocity
    publish_cmd: true

    # Publish wheel data
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 4.0
    linear.x.min_velocity: -4.0
    linear.x.max_acceleration: 100.0
    linear.x.min_acceleration: -100.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.max_acceleration: 100.0
    angular.z.min_acceleration: -100.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0
