---
- topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  ign_type_name: ignition.msgs.Clock
  direction: IGN_TO_ROS
- topic_name: /rpm/sensors/front/lidar3d/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  ign_type_name: ignition.msgs.LaserScan
  direction: IGN_TO_ROS
- topic_name: /rpm/sensors/front/lidar3d/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  ign_type_name: ignition.msgs.PointCloudPacked
  direction: IGN_TO_ROS
- topic_name: /rpm/sensors/rear/lidar3d/scan
  ros_type_name: sensor_msgs/msg/LaserScan
  ign_type_name: ignition.msgs.LaserScan
  direction: IGN_TO_ROS
- topic_name: /rpm/sensors/rear/lidar3d/points
  ros_type_name: sensor_msgs/msg/PointCloud2
  ign_type_name: ignition.msgs.PointCloudPacked
  direction: IGN_TO_ROS
- topic_name: /reference_frame_pose
  ros_type_name: geometry_msgs/msg/PoseStamped
  ign_type_name: ignition.msgs.Pose
  direction: IGN_TO_ROS
- topic_name: /rpm/sensors/front/imu/imu/data
  ros_type_name: sensor_msgs/msg/Imu
  ign_type_name: ignition.msgs.IMU
  direction: IGN_TO_ROS
- ign_topic_name: /world/visualize_lidar_world/model/bautiro/joint_state
  ros_topic_name: /joint_states
  ros_type_name: sensor_msgs/msg/JointState
  ign_type_name: ignition.msgs.Model
  direction: IGN_TO_ROS
  lazy: false