"MoveLiftAbsolute":
  parameters:
    - name: Zielhoehe
      type: numeric
      value: 1
      # Einheiten in Meter
      min: 0.0
      max: 2.46
      step_size: 0.01
    - name: speed_mult
      type: numeric
      value: 1
      min: 1.0
      max: 10.0
      step_size: 1
  description: Lift in der Höhe verstellen
