# === Major modes ====
sensor_mode: multi_sensor

# scan_combiner/lidars: [ouster_FL, ouster_RR] #[vlp_FL, vlp_RR] #[ouster_FL, ouster_RR] #[ouster_FR, vlp_FL, vlp_RR] #[vlp_RR]
scan_combiner/lidars: [ouster_RL, ouster_FR]

ouster_RL/type: ouster
ouster_RL/lidar_filter/class: interpolator3
ouster_RL/lidar_filter/name: interpolator3
ouster_RL/topic_name: "/rpm/sensors/rear/lidar3d/points" 
ouster_RL/base_link_to_sensor:  [-0.992, 0.467, 0.598, 0.006, 0.002, 0.932, -0.364]  #calibration taken from TS60 04.05.2023

ouster_FR/type: ouster 
ouster_FR/lidar_filter/class: interpolator3
ouster_FR/lidar_filter/name: interpolator3
ouster_FR/topic_name: "/rpm/sensors/front/lidar3d/points" 
ouster_FR/base_link_to_sensor:  [0.938, -0.480, 0.599, -0.012, -0.030, 0.346, 0.938]  #calibration taken from TS60 04.05.2023
#ouster_FR/base_link_to_sensor:  [-0.050, -0.938, 0.015, 0.0, 0.0, -0.9125427012946495, 0.4089814400603821]  #  UPDATE NEEDED! calibration taken from TS60 15.02.2023
# [-0.050, -0.938, 0.015, 0.0, 0.0, -0.9243996907446073, 0.381425237433595]

# == Lidar Filter ==
lidar_filter/class: interpolator3
lidar_filter/name: interpolator3
# == Interpolator3 ==
interpolator3/min_range_m: 2.5
interpolator3/max_range_m: 50.0
#interpolator3/filter_mode: vertical
#interpolator3/threshold_vertical_rad: 0.15
interpolator3/filter_mode: ray_filter

interpolator3/enable_undistortion: true
interpolator3/enable_publish_pointclouds: true
interpolator3/shall_create_full_point_cloud: true
interpolator3/estimate_scan_duration_from_header_stamp: false
interpolator3/default_scan_duration: 0.1

introspection/tracker/enabled: false
introspection/lidar_odometry/enabled: false

# === enable/disable Z estimation globally ===
optimizer/enable_estimate_z: true
slam/enable_z_matching_for_odo: true
slam/enable_z_matching_for_loop_closures: true
